name: My Workflow
run-name: >
  $(date +'%Y.%m.%d').${{ github.run_number }}
on:
  workflow_dispatch:

jobs:
  build:
    name: Build Stage
    runs-on: ubuntu-latest
    steps:
      - name: Print Build Start
        run: echo "🚧 Build stage started"

      - name: Simulate Build
        run: echo "Building the application..."

      - name: Print Build Complete
        run: echo "✅ Build stage completed"


